version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: jobq-postgres
    environment:
      POSTGRES_USER: jobq
      POSTGRES_PASSWORD: jobq
      POSTGRES_DB: jobq
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: jobq-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6380:6379"
volumes:
  pgdata:
